import { NO_SCRAMBLE, type LevelConfig } from './types';

/**
 * Locked v1 roadmap: 20 levels across 4 chapters, matching the Free (1-5) /
 * Pack I (6-10) / Pack II (11-20) monetization tiers. See project memory
 * `mazeshift-level-plan` for the full design rationale per level.
 *
 * Grids are deliberately large and dense even early on — the maze itself is
 * the challenge in chapter 1, before monsters or utilities exist, so it has
 * to take real time and real exploration to solve.
 */
export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    chapter: 1,
    title: 'First Steps',
    grid: { width: 14, height: 18 },
    scramble: NO_SCRAMBLE,
    monsters: [],
    utilities: [],
    inventoryCap: 0,
  },
  {
    id: 2,
    chapter: 1,
    title: 'Longer Path',
    grid: { width: 16, height: 20 },
    scramble: NO_SCRAMBLE,
    monsters: [],
    utilities: [],
    inventoryCap: 0,
  },
  {
    id: 3,
    chapter: 1,
    title: "It's Changing",
    grid: { width: 15, height: 19 },
    scramble: { enabled: true, minIntervalSec: 20, maxIntervalSec: 23, falseAlarmChance: 0, intensity: 24 },
    monsters: [],
    utilities: [],
    inventoryCap: 0,
  },
  {
    id: 4,
    chapter: 1,
    title: 'Faster',
    grid: { width: 14, height: 18 },
    scramble: { enabled: true, minIntervalSec: 15, maxIntervalSec: 17, falseAlarmChance: 0.1, intensity: 24 },
    monsters: [],
    utilities: [],
    inventoryCap: 0,
  },
  {
    id: 5,
    chapter: 1,
    title: 'The First Mark',
    grid: { width: 16, height: 20 },
    scramble: { enabled: true, minIntervalSec: 15, maxIntervalSec: 18, falseAlarmChance: 0.15, intensity: 30 },
    monsters: [],
    utilities: ['phase'],
    inventoryCap: 2,
  },
  {
    id: 6,
    chapter: 2,
    title: 'Sealed Routes',
    grid: { width: 16, height: 20 },
    scramble: { enabled: true, minIntervalSec: 14, maxIntervalSec: 17, falseAlarmChance: 0.15, intensity: 30 },
    monsters: [],
    utilities: ['phase'],
    inventoryCap: 2,
  },
  {
    id: 7,
    chapter: 2,
    title: 'Second Sign',
    grid: { width: 17, height: 21 },
    scramble: { enabled: true, minIntervalSec: 14, maxIntervalSec: 17, falseAlarmChance: 0.15, intensity: 36 },
    monsters: [],
    utilities: ['phase', 'destroy'],
    inventoryCap: 2,
  },
  {
    id: 8,
    chapter: 2,
    title: 'Something Hunts',
    grid: { width: 15, height: 19 },
    scramble: NO_SCRAMBLE,
    monsters: ['hunter'],
    utilities: ['phase', 'destroy'],
    inventoryCap: 2,
  },
  {
    id: 9,
    chapter: 2,
    title: 'Hunted & Shifting',
    grid: { width: 16, height: 20 },
    scramble: { enabled: true, minIntervalSec: 13, maxIntervalSec: 16, falseAlarmChance: 0.15, intensity: 36 },
    monsters: ['hunter'],
    utilities: ['phase', 'destroy'],
    inventoryCap: 2,
  },
  {
    id: 10,
    chapter: 2,
    title: 'BOOM',
    grid: { width: 17, height: 21 },
    scramble: { enabled: true, minIntervalSec: 13, maxIntervalSec: 16, falseAlarmChance: 0.2, intensity: 39 },
    monsters: ['hunter', 'brute'],
    utilities: ['phase', 'destroy'],
    inventoryCap: 2,
  },
  {
    id: 11,
    chapter: 3,
    title: 'Walls Lie',
    grid: { width: 18, height: 22 },
    scramble: { enabled: true, minIntervalSec: 12, maxIntervalSec: 15, falseAlarmChance: 0.2, intensity: 42 },
    monsters: ['hunter', 'wraith'],
    utilities: ['phase', 'destroy'],
    inventoryCap: 2,
  },
  {
    id: 12,
    chapter: 3,
    title: 'Choose Wisely',
    grid: { width: 18, height: 22 },
    scramble: { enabled: true, minIntervalSec: 12, maxIntervalSec: 15, falseAlarmChance: 0.2, intensity: 42 },
    monsters: ['hunter', 'wraith'],
    utilities: ['phase', 'destroy', 'scramble'],
    inventoryCap: 2,
  },
  {
    id: 13,
    chapter: 3,
    title: 'Scarcity',
    grid: { width: 18, height: 22 },
    scramble: { enabled: true, minIntervalSec: 11, maxIntervalSec: 14, falseAlarmChance: 0.2, intensity: 42 },
    monsters: ['hunter', 'wraith'],
    utilities: ['phase', 'destroy', 'scramble'],
    inventoryCap: 1,
  },
  {
    id: 14,
    chapter: 3,
    title: 'Everything',
    grid: { width: 19, height: 23 },
    scramble: { enabled: true, minIntervalSec: 11, maxIntervalSec: 14, falseAlarmChance: 0.2, intensity: 45 },
    monsters: ['hunter', 'wraith', 'brute', 'stalker'],
    utilities: ['phase', 'destroy', 'scramble', 'dash'],
    inventoryCap: 2,
  },
  {
    id: 15,
    chapter: 3,
    title: 'The Maze Knows You',
    grid: { width: 21, height: 25 },
    scramble: { enabled: true, minIntervalSec: 10, maxIntervalSec: 13, falseAlarmChance: 0.25, intensity: 54 },
    monsters: ['hunter', 'wraith', 'brute', 'stalker'],
    utilities: ['phase', 'destroy', 'scramble', 'dash'],
    inventoryCap: 2,
    isBoss: true,
  },
  {
    id: 16,
    chapter: 4,
    title: 'Being Watched',
    grid: { width: 15, height: 19 },
    scramble: NO_SCRAMBLE,
    monsters: ['watcher'],
    utilities: ['phase', 'destroy', 'scramble', 'dash'],
    inventoryCap: 2,
  },
  {
    id: 17,
    chapter: 4,
    title: 'Predicted',
    grid: { width: 17, height: 21 },
    scramble: NO_SCRAMBLE,
    monsters: ['stalker', 'watcher'],
    utilities: ['phase', 'destroy', 'scramble', 'dash', 'shield'],
    inventoryCap: 2,
  },
  {
    id: 18,
    chapter: 4,
    title: 'The Gallery',
    grid: { width: 20, height: 24 },
    scramble: { enabled: true, minIntervalSec: 10, maxIntervalSec: 13, falseAlarmChance: 0.2, intensity: 54 },
    monsters: ['hunter', 'wraith', 'brute', 'stalker', 'watcher'],
    utilities: ['phase', 'destroy', 'scramble', 'dash', 'shield', 'trap'],
    inventoryCap: 2,
  },
  {
    id: 19,
    chapter: 4,
    title: 'Nothing Left to Spare',
    grid: { width: 20, height: 25 },
    scramble: { enabled: true, minIntervalSec: 9, maxIntervalSec: 12, falseAlarmChance: 0.25, intensity: 57 },
    monsters: ['wraith', 'stalker', 'watcher'],
    utilities: ['phase', 'destroy', 'scramble', 'dash', 'shield', 'trap'],
    inventoryCap: 1,
  },
  {
    id: 20,
    chapter: 4,
    title: 'The Maze Fights Back',
    grid: { width: 23, height: 28 },
    scramble: { enabled: true, minIntervalSec: 8, maxIntervalSec: 11, falseAlarmChance: 0.25, intensity: 66 },
    monsters: ['hunter', 'wraith', 'brute', 'stalker', 'watcher'],
    utilities: ['phase', 'destroy', 'scramble', 'dash', 'shield', 'trap'],
    inventoryCap: 1,
    isBoss: true,
  },
];

export function getLevel(id: number): LevelConfig | undefined {
  return LEVELS.find((level) => level.id === id);
}
